// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace Api.Sdk
{
    public static partial class Lending20APIV1Extensions
    {
    }
}
