// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Api.Sdk.Models
{
    public partial class BorrowerDto
    {
        private string _accountId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AccountId
        {
            get { return this._accountId; }
            set { this._accountId = value; }
        }
        
        private string _cobranderId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string CobranderId
        {
            get { return this._cobranderId; }
            set { this._cobranderId = value; }
        }
        
        private bool? _eDisclosureConsent;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? EDisclosureConsent
        {
            get { return this._eDisclosureConsent; }
            set { this._eDisclosureConsent = value; }
        }
        
        private string _emailAddress;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string EmailAddress
        {
            get { return this._emailAddress; }
            set { this._emailAddress = value; }
        }
        
        private bool? _emailConsent;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? EmailConsent
        {
            get { return this._emailConsent; }
            set { this._emailConsent = value; }
        }
        
        private string _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _partnerId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PartnerId
        {
            get { return this._partnerId; }
            set { this._partnerId = value; }
        }
        
        private int? _position;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Position
        {
            get { return this._position; }
            set { this._position = value; }
        }
        
        private string _siteProfileId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string SiteProfileId
        {
            get { return this._siteProfileId; }
            set { this._siteProfileId = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the BorrowerDto class.
        /// </summary>
        public BorrowerDto()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken accountIdValue = inputObject["AccountId"];
                if (accountIdValue != null && accountIdValue.Type != JTokenType.Null)
                {
                    this.AccountId = ((string)accountIdValue);
                }
                JToken cobranderIdValue = inputObject["CobranderId"];
                if (cobranderIdValue != null && cobranderIdValue.Type != JTokenType.Null)
                {
                    this.CobranderId = ((string)cobranderIdValue);
                }
                JToken eDisclosureConsentValue = inputObject["EDisclosureConsent"];
                if (eDisclosureConsentValue != null && eDisclosureConsentValue.Type != JTokenType.Null)
                {
                    this.EDisclosureConsent = ((bool)eDisclosureConsentValue);
                }
                JToken emailAddressValue = inputObject["EmailAddress"];
                if (emailAddressValue != null && emailAddressValue.Type != JTokenType.Null)
                {
                    this.EmailAddress = ((string)emailAddressValue);
                }
                JToken emailConsentValue = inputObject["EmailConsent"];
                if (emailConsentValue != null && emailConsentValue.Type != JTokenType.Null)
                {
                    this.EmailConsent = ((bool)emailConsentValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((string)idValue);
                }
                JToken partnerIdValue = inputObject["PartnerId"];
                if (partnerIdValue != null && partnerIdValue.Type != JTokenType.Null)
                {
                    this.PartnerId = ((string)partnerIdValue);
                }
                JToken positionValue = inputObject["Position"];
                if (positionValue != null && positionValue.Type != JTokenType.Null)
                {
                    this.Position = ((int)positionValue);
                }
                JToken siteProfileIdValue = inputObject["SiteProfileId"];
                if (siteProfileIdValue != null && siteProfileIdValue.Type != JTokenType.Null)
                {
                    this.SiteProfileId = ((string)siteProfileIdValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type BorrowerDto
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.AccountId != null)
            {
                outputObject["AccountId"] = this.AccountId;
            }
            if (this.CobranderId != null)
            {
                outputObject["CobranderId"] = this.CobranderId;
            }
            if (this.EDisclosureConsent != null)
            {
                outputObject["EDisclosureConsent"] = this.EDisclosureConsent.Value;
            }
            if (this.EmailAddress != null)
            {
                outputObject["EmailAddress"] = this.EmailAddress;
            }
            if (this.EmailConsent != null)
            {
                outputObject["EmailConsent"] = this.EmailConsent.Value;
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id;
            }
            if (this.PartnerId != null)
            {
                outputObject["PartnerId"] = this.PartnerId;
            }
            if (this.Position != null)
            {
                outputObject["Position"] = this.Position.Value;
            }
            if (this.SiteProfileId != null)
            {
                outputObject["SiteProfileId"] = this.SiteProfileId;
            }
            return outputObject;
        }
    }
}
