// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace DH.Lending.Borrower.Api.Sdk.V1.Lending.Rest.Client
{
    public static partial class LendingRestClientExtensions
    {
    }
}
